### ISSUE TITLE
Merging small components in 3D fails with `node is already root`

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/PyChunkedGraph#121]
Example: https://nkem-multicut-dot-neuromancer-seung-import.appspot.com/?json_url=https://www.dynamicannotationframework.com/nglstate/5683257223938048

**Comment by sdorkenw** [comment]
This was caused by the transition to the new format. All meshes (and fragments) are now referred to by their root id in neuroglancer. A call for the root id of this id then failed do to an exception in get_root that disallowed asking for root ids of root ids (https://github.com/seung-lab/PyChunkedGraph/blob/master/pychunkedgraph/backend/chunkedgraph.py#L1129). this exception was removed in 63984fb.
